#!/bin/bash

#SBATCH -J CVDM_TRAIN
#SBATCH -p general
#SBATCH --mail-user=cwseitz@iu.edu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=14:00:00
#SBATCH --mem=0
#SBATCH -A r01151

#Load any modules that your program needs
module load conda
conda activate st_cvdm

cd git/st_cvdm
python mains/train.py --config-path=configs/st-st_cvdm_train-1.yaml
#srun ./my_program my_program_arguments
