task: "loco"

model:
  noise_model_type: "unet"
  alpha: 0.001
  load_weights: "/N/slate/cwseitz/cvdm/Sim/4x/N-200_N0-500-1000/weights/model_12000_186a018f-db1a-4da8-94cd-afef3bf968b6.h5" 
  load_mu_weights: null
  snr_expansion_n: 1
  zmd: False
  diff_inp: False

training:
  lr: 0.0001
  epochs: 50
  
eval:
  output_path: "/N/slate/cwseitz/cvdm/Sim/4x/N-200_N0-500-1000/eval_data/N200-7"
  generation_timesteps: 200
  checkpoint_freq: 1000
  log_freq: 10
  image_freq: 100
  val_freq: 200
  val_len: 10

data:
  dataset_path: "/N/slate/cwseitz/cvdm/Sim/4x/N-200_N0-500-1000/eval_data/N200-7/"
  n_samples: 20
  batch_size: 2
  im_size: 256

neptune:
  name: "CVDM"
  project: "cwseitz/test"
