task: "loco"

model:
  noise_model_type: "unet"
  alpha: 0.001
  load_weights: "/N/slate/cwseitz/cvdm/Tubes/Real/Sim/weights/model_12000_f08ace5a-7ccd-4077-993b-b739702358df.h5" 
  load_mu_weights: null
  snr_expansion_n: 1
  zmd: False
  diff_inp: False

training:
  lr: 0.0001
  epochs: 50
  
eval:
  output_path: "/N/slate/cwseitz/cvdm/Tubes/Real/Real_Long_Sequence/eval"
  generation_timesteps: 200
  checkpoint_freq: 1000
  log_freq: 10
  image_freq: 100
  val_freq: 200
  val_len: 10

data:
  dataset_path: "/N/slate/cwseitz/cvdm/Tubes/Real/Real_Long_Sequence/eval/"
  n_samples: 3000
  batch_size: 1
  im_size: 256

neptune:
  name: "CVDM"
  project: "cwseitz/test"
