task: "loco"

model:
  noise_model_type: "unet"
  alpha: 0.001
  load_weights: "/N/slate/cwseitz/st-cvdm/GRF/weights/model_12000_ed34f210-3003-478a-bc5d-adfe52305b58.h5" 
  load_mu_weights: null
  snr_expansion_n: 1
  zmd: False
  diff_inp: False

training:
  lr: 0.0001
  epochs: 50
  
eval:
  output_path: "/N/slate/cwseitz/st-cvdm/GRF/eval_data"
  generation_timesteps: 200
  checkpoint_freq: 1000
  log_freq: 10
  image_freq: 100
  val_freq: 200
  val_len: 10

data:
  dataset_path: "/N/slate/cwseitz/st-cvdm/GRF/eval_data/"
  n_samples: 20
  batch_size: 2
  im_size: 64

neptune:
  name: "CVDM"
  project: "cwseitz/test"
