task: "loco"

model:
  noise_model_type: "unet"
  alpha: 0.001
  load_weights: "/N/slate/cwseitz/cvdm/Sim/2x/Sim_CMOS-256-1000-250s-0-1p0-1p0/weights/model_12000_87ca0605-0942-4b49-8e3a-db2fe1d13321.h5" 
  load_mu_weights: null
  snr_expansion_n: 1
  zmd: False
  diff_inp: False

training:
  lr: 0.0001
  epochs: 50
  
eval:
  output_path: "/N/slate/cwseitz/cvdm/H2B/2x"
  generation_timesteps: 200
  checkpoint_freq: 1000
  log_freq: 10
  image_freq: 100
  val_freq: 200
  val_len: 10

data:
  dataset_path: "/N/slate/cwseitz/cvdm/H2B/2x/"
  n_samples: 500
  batch_size: 2
  im_size: 256

neptune:
  name: "CVDM"
  project: "cwseitz/test"
